version: "3.5"
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./tmp/db/var/lib/sqlite3/data
    stdin_open: true
    tty: true
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/teste-ruby-airan
    ports:
      - "3000:3000"
    depends_on:
      - db